using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using WMPLib;

namespace AnimacionSanValentin.Clases
{
    class Mensaje
    {
        private WindowsMediaPlayer sound = new WindowsMediaPlayer();

        public void AnimacionPantalla()
        {
            sound.URL = "cancion.mp3";
            sound.controls.play();

            for (int i = 0; i < 5; i++)
            {
                int j = 0;
                Console.ForegroundColor = (ConsoleColor)new Random().Next(1, 16);
                Console.SetCursorPosition(5, j);
                Console.WriteLine();
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine();
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine();
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine();
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                   .*/(((((/*,                                                 ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                ,(###(/**//(##%#(,.                                            ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("              ,#%(*           .*(#%#,        ....                              ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("            ./%/.                  *##(####((((((###%#(*.                      ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("            (#(                    /##*.            .,(#%#/.                   ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("           .#%,                  *(,                    ,(##*.                 ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("           .#%,                                           .(##.                ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("            /##.                                            (##                ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("             ,#(*                                           ,(#.               ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("              ,##*.                                         *##.               ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("               ,(%#,                                       .#%/                ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                 ./#(*                                 .,(#%%####(/,           ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                   ,#%(                            .*/#%%##(*,,,*/(###,        ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                    .*##/                      ,*(#%%%#/,           /##*.      ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                      .##(*                ,(####//((/                (#(      ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                        .##(          *(###/..   ,/.                  .##,     ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                         .*#/.     ,###*,        .                    .#%,     ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                           /##.  /#%/,                                ,##.     ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                            (#((###%*                                 /%(      ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                             .(*.  (#(                              *(#*.      ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                   .(#(.                          ,(%#,        ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                     ,##/                     ./(##(,          ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                      .##(,             .,*(###(/,.            ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                        ,##,       ,(###(/,.                   ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                         /#(   .,(##/,                         ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                         ./#. /##*.                            ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                          ,###/.                               ");
                Thread.Sleep(100);
                j++;
                Console.SetCursorPosition(5, j);
                Console.WriteLine("                                           /*.                                 ");
                Thread.Sleep(100);

                Console.WriteLine();
                Console.WriteLine();
                Console.WriteLine();
                int f =5;   
                int h=15;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("H");
                Thread.Sleep(100);
                h++;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine(" a");
                Thread.Sleep(100);
                h++;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("  p");
                Thread.Sleep(100);
                h++;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("   p");
                Thread.Sleep(100);
                h++;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("    y");
                Thread.Sleep(100);
                h++;
                Console.SetCursorPosition(f,h);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("      ");
                Thread.Sleep(100);
                //Valentines
                h++;
                int e = 15;
                int g = 18;
                Console.SetCursorPosition(e,g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("V");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e,g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine(" a");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e,g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("  l");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e,g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("   e");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("    n");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("     t");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("      i");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("       n");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("        e'");
                Thread.Sleep(100);
                g++;
                Console.SetCursorPosition(e, g);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("         s");
                Thread.Sleep(100);

                int x = 29;
                int y = 26;
                Console.SetCursorPosition(x,y);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("D");
                Thread.Sleep(100);
                y++;
                Console.SetCursorPosition(x, y);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine(" a");
                Thread.Sleep(100);
                y++;
                Console.SetCursorPosition(x, y);
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("  y");
                Thread.Sleep(100);
                
            }

        }


    }
}
